# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 213e380dfd9fd22b96f355130d00c95eee6ab7b3b118695d797c96feb61be58a3caaf916a585dcccbff85a1a4aa58305b45bdfddc8bd16c36dfd98e9fe2bf83f

test:
  secret_key_base: ba1ee489699401aa90b26fb592c0cac1dafcfd54033b684aa3daa693d505472d40afa1fed0b04fdbfd9457b0b44bea4b689b02c748de365f2195f016eb297741

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
